DBookmark/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import bookmark
from bookmark import views
from bookmark.views import BookmarkListView

urlpatterns = [
    # path('', BookmarkListView.as_view(), name='home'),
    path('', bookmark.views.list_bookmark, name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FooDiew/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import food
from food import views
from food.views import FoodListView

urlpatterns = [
    path('', food.views.list_food, name='home'),
    path('food/', include('food.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),  # accounts:register
    path('login/', views.my_login, name='login'),
    path('logout/', views.my_logout, name='logout'),
]

food/urls.py
from django.urls import path

from food import views
from food.views import FoodListView, FoodCreateView, FoodDetailView, FoodUpdateView, FoodDeleteView

app_name = 'food'

urlpatterns = [
    path('list/', views.list_food, name='list'),
    path('add/', views.create_food, name='add'),
    path('detail/<int:pk>/', views.detail_food, name='detail'),
    path('edit/<int:pk>/', views.modify_food, name='edit'),
    path('delete/<int:pk>/', views.delete_food, name='delete'),
]

accounts/models.py
from django.conf import settings
from django.db import models

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField('별명', max_length=20)

    def __str__(self):
        return f'{self.nickname}({self.user.username})'

food/models.py
from django.db import models
from django.shortcuts import resolve_url

from accounts.models import Profile


class Food(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return resolve_url('food:detail', pk=self.pk)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import models

from accounts.models import Profile
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    username = forms.CharField(label='사용자명', widget=forms.TextInput(attrs={
        'pattern': '[a-zA-Z0-9]+',
        'title': '영어 소문자 대문자, 숫자만 가능. 특수문자, 공백 입력 불가능',
    }))
    nickname = forms.CharField(label='별명')

    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('email',)

    def save(self):
        user = super().save()
        new_profile = Profile.objects.create(
            user=user,
            nickname=self.cleaned_data.get('nickname'),
        )
        return new_profile


class LoginForm(models.ModelForm):
    password = forms.CharField(label='패스워드', widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ('username', 'password')

food/forms.py
from django import forms
from food.models import Food


class FoodCreationForm(forms.ModelForm):
    class Meta:
        model = Food
        fields = ['name']

    def save(self, commit=True):
        new_food = Food.objects.create(
            name=self.cleaned_data.get('name'),
        )
        return new_food


class FoodChangeForm(forms.ModelForm):
    class Meta:
        model = Food
        fields = ['name']

accounts/views.py
from django.contrib.auth import logout, authenticate, login, REDIRECT_FIELD_NAME
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from accounts.forms import RegisterForm, LoginForm


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            profile = form.save()
            return render(request, 'accounts/register_done.html', {'profile': profile})
    else:
        form = RegisterForm()
    return render(request, 'accounts/register.html', {'form': form})


def my_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(request.GET.get(REDIRECT_FIELD_NAME) or 'food:list')
        else:
            return render(request, 'accounts/login_fail.html')
    else:
        form = LoginForm()
        return render(request, 'accounts/login.html', {'form': form})


@login_required
def my_logout(request):
    logout(request)
    return redirect('food:list')

food/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from food.forms import FoodCreationForm, FoodChangeForm
from food.models import Food
from accounts.models import Profile

class FoodListView(ListView):
    model = Food

    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            profile = Profile.objects.get(user=user)
            food_list = Food.objects.filter(profile=profile)
        else:
            food_list = Food.objects.all()
            food_list = Food.objects.none()
        return food_list


class FoodCreateView(LoginRequiredMixin, CreateView):
    model = Food
    fields = ['profile', 'name']
    template_name_suffix = '_create'
    success_url = reverse_lazy('food:list')

    def get_initial(self):
        user = self.request.user
        profile = Profile.objects.get(user=user)
        return {'profile': profile}


class FoodDetailView(LoginRequiredMixin, DetailView):
    model = Food


class FoodUpdateView(LoginRequiredMixin, UpdateView):
    model = Food
    fields = ['name']
    template_name_suffix = '_update'


class FoodDeleteView(LoginRequiredMixin, DeleteView):
    model = Food
    success_url = reverse_lazy('food:list')


def list_food(request):
    user = request.user

    if user.is_authenticated:
        profile = Profile.objects.get(user=user)
        food_list = Food.objects.filter(profile=profile)
    else:
        food_list = Food.objects.none()
    return render(request, 'food/food_list.html', {'food_list': food_list})


def detail_food(request, pk):
    food = Food.objects.get(pk=pk)
    return render(request, 'food/food_detail.html', {'food': food})


def delete_food(request, pk):
    if request.method == 'POST':
        food = Food.objects.get(pk=pk)
        food.delete()
        return redirect('food:list')
    else:
        food = Food.objects.get(pk=pk)
        return render(request, 'food/food_confirm_delete.html', {'food': food})


@login_required
def create_food(request):
    if request.method == 'POST':
        form = FoodCreationForm(request.POST)

        if form.is_valid():
            new_food = form.save(commit=False)
            new_food.profile = Profile.objects.get(user=request.user)
            new_food.save()
            return redirect('food:list')
    else:
        form = FoodCreationForm()
    return render(request, 'food/food_create.html', {'form': form})


@login_required
def modify_food(request, pk):
    if request.method == 'POST':
        form = FoodChangeForm(request.POST)
        if form.is_valid():
            food = Food.objects.get(pk=pk)
            food_name = form.cleaned_data.get('name')
            food.save()
            return redirect('food:list')
    else:
        food = Food.objects.get(pk=pk)
        form = FoodChangeForm(instance=food)
    return render(request, 'food/food_update.html', {'form': form})

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %} login {% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="login" class="btn btn-primary">
    </form>
{% endblock %}

accounts/templates/accounts/login_fail.html
{% extends 'base.html' %}

{% block title %} logout {% endblock %}

{% block content %}
    Login Fail!
    <p><a href="{% url 'accounts:register' %}">register</a></p>
    <p><a href="{% url 'accounts:login' %}">login</a></p>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %} register {% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="register" class="btn btn-primary">
    </form>
{% endblock %}

accounts/templates/accounts/register_done.html
{% extends 'base.html' %}

{% block title %} register DONE {% endblock %}

{% block content %}
    {{ profile }}님, 환영합니다! <br><br>
    <a href="{%  url 'accounts:login' %}">로그인</a>
{% endblock %}

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete Bookmark{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}

    <div class="alert alert-danger">
        너 북마크 {{ bookmark }} 진짜 지울거?
    </div>

    <input type="submit" value="ㄹㅇ 삭제" class="btn btn-danger btn-sm">
    <input type="button" value="지우기 ㄴㄴ해" onclick="history.back();" class="btn btn-secondary btn-sm">
</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}

{% block title %}Add Bookmark{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.profile.as_hidden }}
    <p>{{ form.name.label_tag }} {{ form.name }}</p>
    <p>{{ form.url.label_tag }} {{ form.url }}</p>
    <input type="submit" value="Add" class="btn btn-info btn-sm">
</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block title %}Bookmark Detail{% endblock %}

{% block content %}
<h1>{{ bookmark.name }}</h1>
<a href="{{ bookmark.url }}">{{ bookmark.url }}</a><br><br>
<a href="{% url 'bookmark:list' %}" class="btn btn-warning">Go to Bookmark List</a>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% block title %}Bookmark List{% endblock %}

{% block content %}

<div class="btn-group">
    {% if user.is_authenticated %}
        <a href="{% url 'bookmark:add' %}" class="btn btn-info">AddBookmark</a>
        <a href="{% url 'accounts:logout' %}" class="btn btn-danger">Logout</a>
    {% else %}
        <a href="{% url 'accounts:register' %}" class="btn btn-warning">Register</a>
        <a href="{% url 'accounts:login' %}" class="btn btn-primary">Login</a>
    {% endif %}
</div>

<table class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>URL</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    </thead>

    <tbody>
    {% for bookmark in bookmark_list %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td><a href="{% url 'bookmark:detail' pk=bookmark.id %}">{{ bookmark.name }}</a></td>
        <td><a href="{{ bookmark.url }}">{{ bookmark.url }}</a></td>
        <td><a href="{% url 'bookmark:edit' pk=bookmark.pk %}" class="btn btn-primary btn-sm">Edit</a></td>
        <td><a href="{% url 'bookmark:delete' pk=bookmark.pk %}" class="btn btn-danger btn-sm">Delete</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}

{% block title %}Edit Bookmarks{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <input type="submit" value="edit" class="btn btn-warning btn-sm">
</form>
{% endblock %}

food/templates/food/food_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete Bookmark{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}

    <div class="alert alert-danger">
        너 북마크 {{ bookmark }} 진짜 지울거?
    </div>

    <input type="submit" value="ㄹㅇ 삭제" class="btn btn-danger btn-sm">
    <input type="button" value="지우기 ㄴㄴ해" onclick="history.back();" class="btn btn-secondary btn-sm">
</form>
{% endblock %}

food/templates/food/food_create.html
{% extends 'base.html' %}

{% block title %}Add Bookmark{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.profile.as_hidden }}
    <p>{{ form.name.label_tag }} {{ form.name }}</p>
    <p>{{ form.url.label_tag }} {{ form.url }}</p>
    <input type="submit" value="Add" class="btn btn-info btn-sm">
</form>
{% endblock %}

food/templates/food/food_detail.html
{% extends 'base.html' %}

{% block title %}Bookmark Detail{% endblock %}

{% block content %}
<h1>{{ bookmark.name }}</h1>
<a href="{{ bookmark.url }}">{{ bookmark.url }}</a><br><br>
<a href="{% url 'food:list' %}" class="btn btn-warning">Go to Bookmark List</a>
{% endblock %}

food/templates/food/food_list.html
{% extends 'base.html' %}

{% block title %}Bookmark List{% endblock %}

{% block content %}

<div class="btn-group">
    {% if user.is_authenticated %}
        <a href="{% url 'food:add' %}" class="btn btn-info">AddBookmark</a>
        <a href="{% url 'accounts:logout' %}" class="btn btn-danger">Logout</a>
    {% else %}
        <a href="{% url 'accounts:register' %}" class="btn btn-warning">Register</a>
        <a href="{% url 'accounts:login' %}" class="btn btn-primary">Login</a>
    {% endif %}
</div>

<table class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>URL</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    </thead>

    <tbody>
    {% for bookmark in bookmark_list %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td><a href="{% url 'food:detail' pk=bookmark.id %}">{{ bookmark.name }}</a></td>
        <td><a href="{{ bookmark.url }}">{{ bookmark.url }}</a></td>
        <td><a href="{% url 'food:edit' pk=bookmark.pk %}" class="btn btn-primary btn-sm">Edit</a></td>
        <td><a href="{% url 'food:delete' pk=bookmark.pk %}" class="btn btn-danger btn-sm">Delete</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

food/templates/food/food_update.html
{% extends 'base.html' %}

{% block title %}Edit Bookmarks{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_ul }}
    <input type="submit" value="edit" class="btn btn-warning btn-sm">
</form>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%  block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>